### ISSUE TITLE
Help for different types of layouts

### ISSUE THREAD

**Issue by Alex87a** [albertopasqualetto/amazon-deals-telegram-bot#3] opened 2024-03-20 13:50 UTC
Hi, I really appreciate your project! I've been testing it on my Telegram channel for a few days, everything is working perfectly. However, so far I have used the home Offers page (on the Italian store), never managing to do so with other specific pages. In detail, I am working for now on this page: 

https://amzn.to/4clPZGR

My idea was to search in a given category, which is impossible for me since the Bot, as I understand it, searches for menus on the left, such as "50% discount", which is a selectable option to filter offers. So, if I wanted to scrape in this category: 

https://amzn.to/3J5cGBT 

what should I change? 
Thanks in advance for your attention.

**Comment by lorenzo-asquini** [comment] 2024-03-21 15:10
Hi! Thanks for your interest in our project!

Amazon pages have many different layouts, and products are always represented in a different way in the HTML source code. \
In the link you provided, [https://amzn.to/3J5cGBT](https://amzn.to/3J5cGBT), the products are contained in `<div>` elements that have, among their classes, the class `d4xojt-0`. For this reason, it's necessary to search for all such elements, and then search for the urls to the product in the `<a>` elements inside those elements. 

Your example made us notice that, for dynamically loaded pages, not all products are loaded from the beginning, so it's necessary to scroll the page to make new products be loaded.

Here's the modified function `get_all_deals_ids()` adapted for [https://amzn.to/3J5cGBT](https://amzn.to/3J5cGBT). You will need to import the library `time` with `import time`. Let us know if you have any other issues!

```python
def get_all_deals_ids():
    deals_page = "https://amzn.to/3J5cGBT"
    selenium_driver = start_selenium()

    print("Starting taking all urls")

    try:
        selenium_driver.get(deals_page)

        # products are dynamically loaded, so it's necessary to load all of them in order to not loose any
        # scrolling the page a few times makes sure that all products have been loaded
        deals_urls = []
        for _ in range(3):
            
            selenium_driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(3)  # 3 seconds is a good compromise. It may be necessary to increase the delay on a slow connection
        
            # products are contained in a <div> with class 'd4xojt-0'
            # inside each <div>, there is an <a> element with the link of a product. There are no submenus
            # no problem if some urls are saved multiple times because, at the end, the ids are considered as a set
            deals_urls += [div.find_elements(By.TAG_NAME, "a")[0].get_attribute("href") for div in
                             selenium_driver.find_elements(By.CSS_SELECTOR, "div[class*='d4xojt-0']")]

        # keep only product ids because they can be easily used to create the link for that product
        product_ids = [extract_product_id(url) for url in deals_urls if
                       extract_product_id(url) is not None and extract_product_id(url) != '']

        selenium_driver.quit()  # close everything that was created. Better not to keep driver open for much time
        return [*set(product_ids)]  # remove duplicates

    except Exception as e:
        print(e)
        selenium_driver.quit()  # close everything that was created. Better not to keep driver open for much time
        return []  # error, no ids taken
```

**Comment by lorenzo-asquini** [comment] 2024-03-21 22:50
The idea is correct, but you are searching for a class name that is too broad, meaning that it is used in much more places on the webpage than just for the product cards. In the future, when searching for a suitable class to use, try to search for it in the source code of the page and make sure that it is present (almost) only in the elements you want. \
The class for `<div>` elements you tried to search for is also used for elements that do not contain an `<a>` element, so this gives problems.

On the page you provided ([https://amzn.to/43rBtcC](https://amzn.to/43rBtcC)), it's easier to search for the ids of the products because the `<a>` elements contain a searchable class. The code snippet to use in this case is:

```python
deals_urls += [e.get_attribute("href") for e in
                           selenium_driver.find_elements(By.CSS_SELECTOR, "a[class*='a-link-normal']")]
```

Although the class `a-link-normal` is present in `<a>` elements that do not relate to products, and it may seem that it is a contradiction with what I said earlier, other functions take care of the additional uses, removing any false positive.

To make sure that the code could also handle searches for ids that are quite broad as this one, I updated the source code, and I invite you to download the latest version before trying the code snippet I provided you.

**Comment by lorenzo-asquini** [comment] 2024-03-22 06:35
It is probably caused by a transparent character that was introduced when copying. See this [stackoverflow question](https://stackoverflow.com/questions/74837978/syntaxerror-invalid-non-printable-character-u00a0-in-python). \
For these kinds of questions, I would suggest using Google by searching for the error directly.

**Comment by lorenzo-asquini** [comment] 2024-03-22 16:27
1) To search if a product is a bestseller, you could try to search if there is an `<i>` element that contains the class `p13n-best-seller-badge` when inside a product page. If such an element is present, you know that the product is a bestseller. \
In your code, when you try to search for that characteristic, you are also using an `if` statement that doesn't seem to make much sense, so I suggest doing as above.

2) If I understand correctly your question, to get the name of the seller, you just need to go one level deeper in the element tree and get the text in the `<a>` element:
```python
seller = product_page_content.xpath('//*[@id="merchantInfoFeature_feature_div"]/div[2]/div/span/a/text()')[0].strip()
```

**Comment by albertopasqualetto** [comment] 2024-03-22 16:39
@Alex87a Honestly we cannot know about classes of all Amazon's pages since they are different in all of them because Amazon is not meant to be scraped like we are doing.

This is basically a project project about scraping, so you should refer to some guides about this topic.

Also it does not make sense to have plenty of information based on scraping (unstable) in this tool (like best-selling and seller's data) since there are official and stable Amazon's APIs for who is a verified affiliate.

At last I notice that you are not using our code.

For these reasons and because your issue is not really related to this project I'll close this PR.

**Closed by albertopasqualetto** 2024-03-22 16:39 UTC
